### ISSUE TITLE
Notification window pops up for a split second, disappears then reappears for another split second then finally goes away

### ISSUE THREAD

**Issue by Smidddd** [scenius-software/angular-toastify#48] opened 2023-05-10 15:20 UTC
Can you please help me with this issue ? I have been troubleshooting everything and nothing seems to change.

**Comment by Lerke** [comment] 2023-05-10 15:30
@Smidddd Gladly! What version of angular-toastify are you using? We recently released a new version, and may have introduced a bug. I see in this issue: https://github.com/scenius-software/angular-toastify/issues/17 that there are troubles with using Bootstrap (or any other framework that uses a `toast` class). Could that be the case here?

**Comment by Smidddd** [comment] 2023-05-10 15:41
im using ^1.0.5 of angular-toastify, and i dont think it has to do with that, i have my toastify toast container inside app.component.html so basically above everything and we only use font awesome for icons. Also the progress bar when the icon first shows up is full for some reason but it takes roughly 5sec for it to show up again when its closing.

**Comment by Smidddd** [comment] 2023-05-10 15:59
I am using bootstrap but that probably isnt the issue because in an earlier project we also used bootstrap and it didnt cause an issue, i actually updated it from 1.0.4 to 1.0.5 and it still works there. The more i look into this the more confused i am :D

**Comment by Lerke** [comment] 2023-05-10 18:04
@Smidddd That does sound  confusing (: - do you maybe have a short video / code example I can use to reproduce the issue?

**Comment by Lerke** [comment] 2024-09-27 22:29
This may be fixed in `2.0.0-dev1`. Since there was no further response on my last comment, I'll close this issue for now. Please re-open if this is still an issue.

**Closed as completed by Lerke** 2024-09-27 22:29 UTC
